### ISSUE TITLE
Game and plugin crashes when i activate it on PCSB00074

### ISSUE THREAD

**Issue by EnekoT2001** [Electry/VGi#5]
Hi, when I push select + L and VGi shows up, the game and the plugin (Assassins Creed III/PCSB00074) just locks up, and I need to do a reset to my vita pushing the power button for several seconds.

Sometimes I'm able to go to the LiveArea by pressing the PS button and then I can close the game.

I'm using the last version (0.6). Idk if it was working with an older version bc I started to poke around with this today.

In all other games I tried (persona 4, NFS: Most Wanted, Hitman Go...) worked okay.

**Comment by Electry** [comment]
Thanks for reporting.
Give v0.7 a go, it should be fixed.

**Comment by EnekoT2001** [comment]
> Thanks for reporting.
> Give v0.7 a go, it should be fixed.

Okay, now works, and also, with the old version in other games like Persona 4 the game went crazy the moment I opened VGi and now nope (maybe due to the input block method you used?). Thank you

Btw, off topic, but how can VGi know the cpu/gpu clocks? Bc I have LOLicon and I have some games in 500mhz but the plugin tells me that it's running at 333, just curious.

**Comment by Electry** [comment]
> the game went crazy the moment I opened VGi and now nope (maybe due to the input block method you used?)

yes

> Btw, off topic, but how can VGi know the cpu/gpu clocks?

VGi polls [scePowerGetArmClockFrequency()](https://docs.vitasdk.org/group__ScePowerUser.html#ga43c4f0084152cff03dc037525a5dd311) and other scePowerGet... functions.

LOLIcon applies clocks by directly writing to [ScePervasiveBaseClk](https://wiki.henkaku.xyz/vita/Pervasive) registers, therefore avoiding the standard Vita ScePower API (which hasn't been made with 500MHz in mind). That's why it reports inaccurate clocks when you use LOLIcon.

**Comment by EnekoT2001** [comment]
> > the game went crazy the moment I opened VGi and now nope (maybe due to the input block method you used?)
> 
> yes
> 
> > Btw, off topic, but how can VGi know the cpu/gpu clocks?
> 
> VGi polls [scePowerGetArmClockFrequency()](https://docs.vitasdk.org/group__ScePowerUser.html#ga43c4f0084152cff03dc037525a5dd311) and other scePowerGet... functions.
> 
> LOLIcon applies clocks by directly writing to [ScePervasiveBaseClk](https://wiki.henkaku.xyz/vita/Pervasive) registers, therefore avoiding the standard Vita ScePower API (which hasn't been made with 500MHz in mind). That's why it reports inaccurate clocks when you use LOLIcon.

Oh, okay, thank you so much for the info: Well, I think we can close this already.
